[package]
name = "ether"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.28.0"
pretty-hex = "0.2.1"
rand = "0.8.4"

